name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
  CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
  SHIFTLEFT_REGION: ${{ secrets.SHIFTLEFT_REGION }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:v1

    - uses: actions/checkout@v4
    - name: Save Image
      run: docker save -o /tmp/docker.tar my-image-name:v1; ls /tmp/

    - uses: actions/checkout@v4
    - name: shiftleft download
      run: cd /tmp; wget https://github.com/cadgo/testpipeline/raw/main/shiftleft; chmod +x shiftleft

    - uses: actions/checkout@v4
    - name: Set Variable
      run: |
        echo "${{env.CHKP_CLOUDGUARD_ID}}"
        #echo "CHKP_CLOUDGUARD_ID=$(echo $CHKP_CLOUDGUARD_ID)" >> $CHKP_CLOUDGUARD_ID
        #echo "CHKP_CLOUDGUARD_SECRET=$(echo $CHKP_CLOUDGUARD_SECRET)" >> $CHKP_CLOUDGUARD_SECRET
        echo "SHIFTLEFT_REGION=$(echo $SHIFTLEFT_REGION)" >> $SHIFTLEFT_REGION
    - name: Scan image
      run: /tmp/shiftleft image-scan -e 9d7c67a2-9a92-4231-b9ff-57f058101d66 -i /tmp/docker.tar
